### ISSUE TITLE
concurrency

### ISSUE THREAD

**Issue by jamesjjk** [srijs/node-clam-engine#3]
Will this library work concurrently, multiple node instances to one clamav engine?

**Comment by srijs** [comment]
Hi!

Can you clarify what you are trying to do?

If you are running multiple node processes concurrently (for instance, via clustering), they can't share state, so you will need to instantiate a clam engine per process.

Doing this however will work just fine, since every engine is self-contained and does not rely on any external clamav daemon.

**Comment by jamesjjk** [comment]
@srijs That was the answer to my query thank you.
